2022-05-09 01:25:25,024 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-09 01:25:25,027 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652039724998"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652059524403"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Invalid Oracle URL specified&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652059524403"/></dao></FailedPersistence>
2022-05-09 01:25:25,029 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@43534f79Object Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 19:55:24.998 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-09 00:00:00.0 logLevel=WARN logTimestamp=2022-05-09 01:25:24.403 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Invalid Oracle URL specified</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-09 01:25:24.403  No Available Datasources.
2022-05-09 01:25:25,030 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652039724998"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652059524403"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: java.sql.SQLException: Invalid Oracle URL specified&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652059524403"/></dao></FailedPersistence>
2022-05-09 01:26:27,282 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-09 01:26:27,286 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652039787217"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652059586738"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652059586738"/></dao></FailedPersistence>
2022-05-09 01:26:27,288 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@6c4eb6baObject Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 19:56:27.217 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-09 00:00:00.0 logLevel=WARN logTimestamp=2022-05-09 01:26:26.738 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-09 01:26:26.738  No Available Datasources.
2022-05-09 01:26:27,289 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652039787217"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652059586738"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652059586738"/></dao></FailedPersistence>
2022-05-09 01:34:05,171 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-09 01:34:05,175 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040245106"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060044624"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060044624"/></dao></FailedPersistence>
2022-05-09 01:34:05,178 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@d31c9a8Object Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 20:04:05.106 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-09 00:00:00.0 logLevel=WARN logTimestamp=2022-05-09 01:34:04.624 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-09 01:34:04.624  No Available Datasources.
2022-05-09 01:34:05,178 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040245106"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060044624"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060044624"/></dao></FailedPersistence>
2022-05-09 01:38:14,906 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-09 01:38:14,910 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040494848"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060294371"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060294371"/></dao></FailedPersistence>
2022-05-09 01:38:14,912 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@5896f421Object Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 20:08:14.848 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-09 00:00:00.0 logLevel=WARN logTimestamp=2022-05-09 01:38:14.371 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-09 01:38:14.371  No Available Datasources.
2022-05-09 01:38:14,913 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040494848"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060294371"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060294371"/></dao></FailedPersistence>
2022-05-09 01:43:20,200 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-09 01:43:20,203 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040800138"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060599593"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060599593"/></dao></FailedPersistence>
2022-05-09 01:43:20,205 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@5d79a786Object Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 20:13:20.138 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-09 00:00:00.0 logLevel=WARN logTimestamp=2022-05-09 01:43:19.593 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-09 01:43:19.593  No Available Datasources.
2022-05-09 01:43:20,206 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040800138"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060599593"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060599593"/></dao></FailedPersistence>
2022-05-09 01:46:34,905 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: java.lang.Throwable: STACK TRACE - Could not save data due to no available datasources
2022-05-09 01:46:34,905 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040994836"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060794295"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060794295"/></dao></FailedPersistence>
2022-05-09 01:46:34,905 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:337)      Persistence Failed: dtv.data2.access.exception.PersistenceException: !!! makePersistent() failure !!! Cannot persist object: dtv.xst.dao.ctl.impl.EventLogEntryDAO@92f1a8dObject Id: [EventLogEntry does not define primary key fields.} DaoState: [INSERT] Id: EventLogEntry does not define primary key fields. Values: createDate=2022-05-08 20:16:34.836 createUserId=0 organizationId=1 retailLocationId=101 workstationId=1 businessDate=2022-05-09 00:00:00.0 logLevel=WARN logTimestamp=2022-05-09 01:46:34.295 source=dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353) threadName=startup loggerCategory=dtv.sysadmin.data.failover logMessage=<Offline>  <DatasourceName>StorePrimary</DatasourceName>  <Cause>dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]</Cause>  <Scope>LAN</Scope></Offline> arrivalTimestamp=2022-05-09 01:46:34.295  No Available Datasources.
2022-05-09 01:46:34,920 [startup] ERROR dtv.data2.access.DaoUtils.logFailedPersistence(DaoUtils.java:351)      <FailedPersistence><dao name="EventLogEntry" cmd="INSERT"><fld id="CreateDate" val="1652040994836"/><fld id="CreateUserId" val="0"/><fld id="OrganizationId" val="1"/><fld id="RetailLocationId" val="101"/><fld id="WorkstationId" val="1"/><fld id="BusinessDate" val="1652054400000"/><fld id="LogLevel" val="WARN"/><fld id="LogTimestamp" val="1652060794295"/><fld id="Source" val="dtv.data2.access.status.StatusMgr.logOffline(StatusMgr.java:353)"/><fld id="ThreadName" val="startup"/><fld id="CriticalToDeliver" val="0"/><fld id="LoggerCategory" val="dtv.sysadmin.data.failover"/><fld id="LogMessage" val="&lt;Offline&gt;&#13;  &lt;DatasourceName&gt;StorePrimary&lt;/DatasourceName&gt;&#13;  &lt;Cause&gt;dtv.data2.access.exception.FailoverException: java.sql.SQLException: Unable to start the Universal Connection Pool: oracle.ucp.UniversalConnectionPoolException: Cannot get Connection from Datasource: com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user [REDACTED]&lt;/Cause&gt;&#13;  &lt;Scope&gt;LAN&lt;/Scope&gt;&#13;&lt;/Offline&gt;&#13;"/><fld id="ArrivalTimestamp" val="1652060794295"/></dao></FailedPersistence>
